[project]
name = "dafny4verifiedtoycompilers"
version = "0.1.0"
description = "A few toy compilers written in Python and verified in Dafny."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "antlr4-python3-runtime>=4.13.2",
    "dafnyruntimepython>=4.9.0",
]
